name1 = "larry"
health = 60
puts name1 + "s health is #{health}"
puts "#{name1}s health is #{3*health}\n"
puts "#{name1}s health is #{health/9}\n"
puts "#{name1}s health is #{health/9.0}\n"
puts "Players:\n\tlarry\n\tcurly\n\tmoe\n\n"
name2 = "curly"
name3 = "moe"
puts "Players:\n\t#{name1}\n\t#{name2}\n\t#{name3}\n\n"
